apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hello-world
build:
  artifacts:
  - image: cxm-dev.common.repositories.cloud.sap/cxm/msgraph-hello
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/msgraph-hello.yaml
